---
version: 2
jobs:
  build:
    working_directory: ~/deltabadger
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          PGHOST: localhost
          PGUSER: deltabadger
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: deltabadger
          POSTGRES_DB: deltabadger_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: your-app-name-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: deltabadger-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      - run: cp ./config/database.yml.example ./config/database.yml

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rspec spec
