---
version: 2
jobs:
  build:
    working_directory: ~/deltabadger
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: deltabadger
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: deltabadger
          POSTGRES_DB: deltabadger_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: deltabadger-bundle-{{ checksum "Gemfile.lock" }}

      - type: cache-restore
        name: Restore yarn cache
        key: deltabadger-yarn-{{ checksum "yarn.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Yarn install dependencies
      - run: yarn install

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: deltabadger-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - type: cache-save
        name: Store yarn cache
        key: deltabadger-yarn-{{ checksum "yarn.lock" }}
        paths:
          - ~/.yarn-cache

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      - run: cp ./config/database.yml.example ./config/database.yml

      # Setup the database
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - run: bundle exec rubocop
      - run: bundle exec bundle audit check --update
      - run: bundle exec rspec spec
