development:
  # adapter: async
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: deltabadger_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: deltabadger_production
