development:
  # adapter: async
  adapter: redis
  url: <%= ENV['REDIS_AWS_URL'] %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_AWS_URL'] %>
  # channel_prefix: appname_production
