development:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['MAX_DB_CONNECTIONS'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  database: deltabadger_new

test:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['MAX_DB_CONNECTIONS'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  database: deltabadger_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['MAX_DB_CONNECTIONS'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  timeout: 5000
