sendgrid_sync_unsubscribes_job:
  cron: "5 0 * * *" # every day at 00:10 UTC
  class: "Sendgrid::SyncUnsubscribesJob"

update_metrics_job:
  cron: "10 */4 * * *" # every 4 hours at minute 10
  class: "UpdateMetricsJob"

send_telegram_update_job:
  cron: "0 7 * * *" # every day at 07:00 UTC
  class: "SendTelegramUpdateJob"

sync_all_tickers_and_assets_job:
  cron: "15 */4 * * *" # every 4 hours at minute 15
  class: "Exchange::SyncAllTickersAndAssetsJob"

fetch_all_assets_data_from_coingecko_job:
  cron: "20 0 * * 1" # At 00:20 UTC on Monday
  class: "Asset::FetchAllAssetsDataFromCoingeckoJob"

# update_bots_in_profit_job:
#   cron: "15 0 * * *" # every day at 00:15 UTC
#   class: "UpdateBotsInProfitJob"


# second_job:
#   cron: "*/30 * * * *" # execute at every 30 minutes
#   class: "HardWorker"
#   queue: hard_worker_long
#   args:
#     hard: "stuff"