
sync_all_tickers_and_assets_job:
  cron: "15 */4 * * *" # every 4 hours at minute 15
  class: "Exchange::SyncAllTickersAndAssetsJob"

fetch_all_assets_data_from_coingecko_job:
  cron: "20 0 * * 1" # At 00:20 UTC on Monday
  class: "Asset::FetchAllAssetsDataFromCoingeckoJob"


# second_job:
#   cron: "*/30 * * * *" # execute at every 30 minutes
#   class: "HardWorker"
#   queue: hard_worker_long
#   args:
#     hard: "stuff"