---
:concurrency: 1
:queues:
  - starting bots
  - api keys validation
  - mailers
  - [binance, 1]
  - [binance.us, 1]
  - [bitbay, 1]
  - [bitfinex, 1]
  - [bitso, 1]
  - [bitstamp, 1]
  - [coinbase pro, 1]
  - [ftx, 1]
  - [ftx.us, 1]
  - [gemini, 1]
  - [kraken, 1]
  - [kucoin, 1]
  - [probit global, 1]
  - [probit, 1]
  - [default, 1]
:limits:
  binance: 1
  binance.us: 1
  bitbay: 1
  bitfinex: 1
  bitso: 1
  bitstamp: 1
  coinbase pro: 1
  ftx: 1
  ftx.us: 1
  gemini: 1
  kraken: 1
  kucoin: 1
  probit: 1
  probit global: 1
